
import { Property, Destination, Testimonial, Review } from './types';

export const PROPERTIES: Property[] = [
  {
    id: 1,
    title: 'Cozy Downtown Loft with City Views',
    location: 'New York, NY',
    pricePerNight: 250,
    rating: 4.9,
    reviewsCount: 120,
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    type: 'Apartment',
    amenities: ['Wifi', 'Kitchen', 'Air conditioning', 'TV', 'City view'],
    description: 'A beautifully designed loft in the heart of the city. Perfect for couples or solo travelers looking to explore the best of New York. Enjoy stunning views from the comfort of your modern and stylish home away from home.',
    host: { name: 'Sarah', avatarUrl: 'https://picsum.photos/seed/host1/100/100' },
    images: [
      'https://picsum.photos/seed/prop1img1/1200/800',
      'https://picsum.photos/seed/prop1img2/1200/800',
      'https://picsum.photos/seed/prop1img3/1200/800',
      'https://picsum.photos/seed/prop1img4/1200/800',
    ],
  },
  {
    id: 2,
    title: 'Sunny Beachfront Villa in Miami',
    location: 'Miami, FL',
    pricePerNight: 500,
    rating: 4.95,
    reviewsCount: 85,
    bedrooms: 3,
    bathrooms: 2,
    guests: 6,
    type: 'Entire home',
    amenities: ['Wifi', 'Pool', 'Beachfront', 'Kitchen', 'Free parking'],
    description: 'Escape to paradise in this luxurious beachfront villa. With a private pool and direct access to the beach, this home offers the ultimate Miami experience. Spacious, modern, and filled with natural light.',
    host: { name: 'Carlos', avatarUrl: 'https://picsum.photos/seed/host2/100/100' },
    images: [
      'https://picsum.photos/seed/prop2img1/1200/800',
      'https://picsum.photos/seed/prop2img2/1200/800',
      'https://picsum.photos/seed/prop2img3/1200/800',
    ],
  },
  {
    id: 3,
    title: 'Mountain Cabin Retreat in Aspen',
    location: 'Aspen, CO',
    pricePerNight: 350,
    rating: 4.88,
    reviewsCount: 98,
    bedrooms: 2,
    bathrooms: 2,
    guests: 4,
    type: 'Entire home',
    amenities: ['Wifi', 'Hot tub', 'Fireplace', 'Kitchen', 'Mountain view'],
    description: 'Experience the beauty of the Rockies in this charming cabin. Features a cozy fireplace, a private hot tub, and breathtaking mountain views. Ideal for a ski trip or a summer getaway.',
    host: { name: 'Emily', avatarUrl: 'https://picsum.photos/seed/host3/100/100' },
    images: [
      'https://picsum.photos/seed/prop3img1/1200/800',
      'https://picsum.photos/seed/prop3img2/1200/800',
    ],
  },
  {
    id: 4,
    title: 'Modern Hollywood Hills Home',
    location: 'Los Angeles, CA',
    pricePerNight: 600,
    rating: 5.0,
    reviewsCount: 45,
    bedrooms: 4,
    bathrooms: 3,
    guests: 8,
    type: 'Entire home',
    amenities: ['Wifi', 'Pool', 'Kitchen', 'City view', 'Home theater'],
    description: 'Live like a star in this stunning Hollywood Hills home. Featuring a sleek modern design, an infinity pool, and panoramic views of Los Angeles, this property is the epitome of luxury.',
    host: { name: 'David', avatarUrl: 'https://picsum.photos/seed/host4/100/100' },
    images: [
        'https://picsum.photos/seed/prop4img1/1200/800',
        'https://picsum.photos/seed/prop4img2/1200/800',
        'https://picsum.photos/seed/prop4img3/1200/800',
        'https://picsum.photos/seed/prop4img4/1200/800',
    ],
  },
   {
    id: 5,
    title: 'Charming Room in Historic Boston',
    location: 'Boston, MA',
    pricePerNight: 120,
    rating: 4.8,
    reviewsCount: 210,
    bedrooms: 1,
    bathrooms: 1,
    guests: 2,
    type: 'Private room',
    amenities: ['Wifi', 'Air conditioning', 'Heating', 'Essentials'],
    description: 'Stay in a cozy private room in a historic brownstone. Located in a beautiful, quiet neighborhood, you are just a short walk away from Boston\'s most famous landmarks and best restaurants.',
    host: { name: 'Michael', avatarUrl: 'https://picsum.photos/seed/host5/100/100' },
    images: [
        'https://picsum.photos/seed/prop5img1/1200/800',
        'https://picsum.photos/seed/prop5img2/1200/800',
    ],
  },
  {
    id: 6,
    title: 'Artistic Studio in San Francisco',
    location: 'San Francisco, CA',
    pricePerNight: 180,
    rating: 4.92,
    reviewsCount: 150,
    bedrooms: 0,
    bathrooms: 1,
    guests: 2,
    type: 'Apartment',
    amenities: ['Wifi', 'Kitchen', 'TV', 'Washer', 'Dryer'],
    description: 'A unique and vibrant studio in the Mission District, filled with local art. The perfect base for exploring the culture, food, and energy of San Francisco. Compact yet fully equipped for a comfortable stay.',
    host: { name: 'Jessica', avatarUrl: 'https://picsum.photos/seed/host6/100/100' },
    images: [
        'https://picsum.photos/seed/prop6img1/1200/800',
        'https://picsum.photos/seed/prop6img2/1200/800',
    ],
  }
];

export const DESTINATIONS: Destination[] = [
  { id: 1, city: 'New York', state: 'NY', imageUrl: 'https://picsum.photos/seed/dest1/400/500' },
  { id: 2, city: 'California', state: 'CA', imageUrl: 'https://picsum.photos/seed/dest2/400/500' },
  { id: 3, city: 'Florida', state: 'FL', imageUrl: 'https://picsum.photos/seed/dest3/400/500' },
  { id: 4, city: 'Colorado', state: 'CO', imageUrl: 'https://picsum.photos/seed/dest4/400/500' },
];

export const TESTIMONIALS: Testimonial[] = [
  { id: 1, author: 'John & Jane Smith', text: '"Our stay was absolutely perfect! The process was so easy, and the place was even better than the pictures. We\'ll definitely be using iStayUSA again!"', location: 'from Chicago' },
  { id: 2, author: 'Alice Johnson', text: '"I found the most unique and charming apartment for my solo trip. iStayUSA made me feel safe and confident in my booking. Highly recommended!"', location: 'from Seattle' },
  { id: 3, author: 'The Garcia Family', text: '"Finding a place for our whole family was a breeze. The filters helped us find exactly what we needed. A wonderful vacation thanks to iStayUSA."', location: 'from Dallas' },
];

export const REVIEWS: Review[] = [
    { id: 1, author: 'Mark', avatarUrl: 'https://picsum.photos/seed/rev1/100/100', date: 'October 2023', rating: 5, text: 'This place was incredible. The views are even better in person. The host was very communicative and helpful. 10/10 would recommend.'},
    { id: 2, author: 'Laura', avatarUrl: 'https://picsum.photos/seed/rev2/100/100', date: 'September 2023', rating: 5, text: 'A truly magical stay. The apartment was spotless, beautifully decorated, and had everything we needed. We didn\'t want to leave!'},
    { id: 3, author: 'Ben', avatarUrl: 'https://picsum.photos/seed/rev3/100/100', date: 'September 2023', rating: 4, text: 'Great location and a very comfortable space. The check-in process was seamless. My only minor issue was the street noise, but that\'s expected in the city center.'},
    { id: 4, author: 'Chloe', avatarUrl: 'https://picsum.photos/seed/rev4/100/100', date: 'August 2023', rating: 5, text: 'The host was an absolute delight. So friendly and gave us amazing local recommendations. The apartment felt like a home away from home.'},
];
